### ISSUE TITLE
Ao inserir um Aluno, não deixar o leitor RFID ler no momento de inserir matrícula

### ISSUE THREAD

**Issue by kyros200** [LucasAmaralPIres/ProjetoFinalUERJ#7]
Atualmente o leitor RFID também pode ler durante o momento de inserir a matrícula e assim então definindo-o como o próprio (a tag do RFID sendo a matrícula do aluno).

**Comment by LucasAmaralPires** [comment]
Também não é possível escrever uma matrícula ao pedir o cartão. Isso foi feito no último commit
